version: 2.1
jobs:
  build:
    docker:
      - image: docker:20.10.18-cli
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/cloudflare-wrangler-image.tar | true
      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=app -t cloudflare-wrangler-image:${CIRCLE_SHA1} .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/cloudflare-wrangler-image.tar cloudflare-wrangler-image
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/cloudflare-wrangler-image.tar

  tag-remote-image:
    docker:
      - image: docker:20.10.18-cli
    parameters:
      tag:
        type: string
    steps:
      - setup_remote_docker
      - run:
          name: Tag Application Docker image
          command: |
            docker tag "cloudflare-wrangler-image:<< parameters.tag >>" "partnerstack/cloudflare-wrangler-image:<< parameters.tag >>"
  publish:
    docker:
      - image: docker:20.10.18-cli
    parameters:
      tag:
        type: string
    steps:
      - setup_remote_docker
      - run:
          name: Push application Docker image
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "partnerstack" --password-stdin
            docker push "partnerstack/cloudflare-wrangler-image:<< parameters.tag >>"

workflows:
  new-main-commit: # After a PR has been merged to main
    jobs:
      - build:
          filters: # Only on new commits in main
            tags:
              ignore: /^v.*/
            branches:
              only: main
      - tag-remote-image:
          requires:
            - build
          tag: ${CIRCLE_SHA1}
      - publish:
          context: [docker-hub]
          requires:
            - tag-remote-image
          tag: ${CIRCLE_SHA1}
