version: 2.1
jobs:
  build:
    docker:
      - image: docker:20.10.18-cli
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/cloudflare-wrangler-image.tar | true
      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=cloudflare-wrangler-image -t cloudflare-wrangler-image:${CIRCLE_SHA1} .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/cloudflare-wrangler-image.tar cloudflare-wrangler-image
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/cloudflare-wrangler-image.tar
      - run:
          name: Tag Application Docker image
          command: |
            docker tag "cloudflare-wrangler-image:${CIRCLE_SHA1}" "partnerstack/cloudflare-wrangler-image:${CIRCLE_SHA1}"
      - run:
          name: Push application Docker image
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "partnerstack" --password-stdin
            docker push "partnerstack/cloudflare-wrangler-image:${CIRCLE_SHA1}"
  tag-and-release:
    docker:
      - image: docker:20.10.18-cli
    steps:
      - setup_remote_docker
      - run:
          name: Pull Image
          command: docker pull "partnerstack/cloudflare-wrangler-image:${CIRCLE_SHA1}"
      - run:
          name: Tag Image with Version
          command: docker tag "partnerstack/cloudflare-wrangler-image:${CIRCLE_SHA1}" "partnerstack/cloudflare-wrangler-image:${CIRCLE_TAG}"
      - run:
          name: Push Image
          command:
            echo "$DOCKERHUB_PASSWORD" | docker login -u "partnerstack" --password-stdin
            docker push "partnerstack/cloudflare-wrangler-image:${CIRCLE_TAG}"


workflows:
  new-main-commit: # After a PR has been merged to main
    jobs:
      - build:
          context: docker-hub
          filters: # Only on new commits in main
            tags:
              ignore: /^v.*/
            branches:
              only: main
  new-release-tag:
    jobs:
      - tag-and-release:
          context: docker-hub
          filters: # Only on Git tags staring with "v"
              tags:
                only: /^v.*/
              branches:
                ignore: /.*/
