version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:current
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=cloudflare-wrangler -t cloudflare-wrangler:${CIRCLE_SHA1} .
      - run:
          name: Tag Application Docker image
          command: |
            docker tag "cloudflare-wrangler:${CIRCLE_SHA1}" "partnerstack/cloudflare-wrangler:${CIRCLE_SHA1}"
      - run:
          name: Push application Docker image
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "partnerstack" --password-stdin
            docker push "partnerstack/cloudflare-wrangler:${CIRCLE_SHA1}"
  tag-and-release:
    machine:
      image: ubuntu-2004:current
      docker_layer_caching: true
    steps:
      - run:
          name: Pull Image
          command: docker pull "partnerstack/cloudflare-wrangler:${CIRCLE_SHA1}"
      - run:
          name: Tag Image with Version
          command: docker tag "partnerstack/cloudflare-wrangler:${CIRCLE_SHA1}" "partnerstack/cloudflare-wrangler:${CIRCLE_TAG}"
      - run:
          name: Push Image
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "partnerstack" --password-stdin
            docker push "partnerstack/cloudflare-wrangler:${CIRCLE_TAG}"


workflows:
  new-main-commit: # After a PR has been merged to main
    jobs:
      - build:
          context: docker-hub
          filters: # Only on new commits in main
            tags:
              ignore: /^v.*/
            branches:
              only: main
  new-release-tag:
    jobs:
      - tag-and-release:
          context: docker-hub
          filters: # Only on Git tags staring with "v"
              tags:
                only: /^v.*/
              branches:
                ignore: /.*/
